/* MiniUPnP Project
 * http://miniupnp.free.fr/ or http://miniupnp.tuxfamily.org/
 * (c) 2006-2008 Thomas Bernard
 * generated by ./genconfig.sh on Sun May 11 23:53:59 UTC 2008 */
#ifndef __CONFIG_H__
#define __CONFIG_H__

#define UPNP_VERSION	"20070827"
#define USE_NETFILTER   1
#ifdef AMPED
#define OS_NAME		    "Amped Wireless"
#define OS_VERSION	    "ver.1"
#define OS_URL		    "http://www.ampedwireless.com/"
#else
#define OS_NAME		    "NETGEAR "
#define OS_VERSION	    "Netgear/1.0"
#define OS_URL		    "http://www.netgear.com/"
#endif

/* syslog facility to be used by miniupnpd */
#define LOG_MINIUPNPD		 LOG_SYSLOG

/* Uncomment the following line to allow miniupnpd to be
 * controlled by miniupnpdctl */
/*#define USE_MINIUPNPDCTL*/

/* Comment the following line to disable NAT-PMP operations */
#define ENABLE_NATPMP

/* Uncomment the following line to enable generation of
 * filter rules with pf */
/*#define PF_ENABLE_FILTER_RULES*/

/* Uncomment the following line to enable caching of results of
 * the getifstats() function */
/*#define ENABLE_GETIFSTATS_CACHING*/
/* The cache duration is indicated in seconds */
#define GETIFSTATS_CACHING_DURATION 2

/* Uncomment the following line to enable multiple external ip support */
/* note : Thas is EXPERIMENTAL, do not use that unless you know perfectly what you are doing */
/*#define MULTIPLE_EXTERNAL_IP*/

/* Comment the following line to use home made daemonize() func instead
 * of BSD daemon() */
#define USE_DAEMON

/* Uncomment the following line to enable lease file support */
#define ENABLE_LEASEFILE

/* Define one or none of the two following macros in order to make some
 * clients happy. It will change the XML Root Description of the IGD.
 * Enabling the Layer3Forwarding Service seems to be the more compatible
 * option. */
/*#define HAS_DUMMY_SERVICE*/
#define ENABLE_L3F_SERVICE

#define ENABLE_LANDEVICE

/* Experimental UPnP Events support. */
#define ENABLE_EVENTS
/* Comment the following line to disable Wi-Fi Protected Setup support */
#define ENABLE_WSC_SERVICE

//#define DEBUG

#ifdef DEBUG

#if 0
#define SYSLOG syslog
#else
#define _SC_DEBUG_ENABLE_
#include "sc_debug.h"
#define SYSLOG(level, str, args...) do {SC_CFPRINTF(str, ## args); SC_XCFPRINTF("\n");}while(0)
#endif

#else  /* DEBUG */
#define SYSLOG(...)
#endif /* DEBUG */

#define LOG_ONE_MSG(level, str, args...) do { printf(str, ## args); \
    printf("\n"); \
    syslog(level, str, ## args); } while(0)

#endif
