#ifndef SC_LED_ID_H
#define SC_LED_ID_H

#define SC_LED_ID_START		10
#define LAN_LED_ID_START	10
#define WAN0_GREEN_LED_ID_START	20
#define WAN0_RED_LED_ID_START	30
#define WLAN_LED_ID_START	40
#define WPS_LED_ID_START	45
#define DSL_LED_ID_START         50
#define USB_LED_ID_START	60
#define PWR_LED_ID_START	70
#define BADGE_LED_ID_START	75
#define OTHER_LED_ID_START       80
#define PUSH_BTN_ID_START	90
#define SC_LED_ID_END		99

/* LAN LED */
enum {
    LAN_GREEN_LED = LAN_LED_ID_START, 
    LAN_AMBER_LED,
    LAN_1_GREEN_LED, 
    LAN_1_AMBER_LED,
    LAN_2_GREEN_LED, 
    LAN_2_AMBER_LED,
    LAN_3_GREEN_LED, 
    LAN_3_AMBER_LED,
    LAN_4_GREEN_LED, 
    LAN_4_AMBER_LED,
	WAKE_LED,
};



/* WAN GREEN LED */
enum {
	WAN0_GREEN_LED = WAN0_GREEN_LED_ID_START,
	WAN1_GREEN_LED,
	WAN2_GREEN_LED,
	WAN3_GREEN_LED,
	WAN4_GREEN_LED,
	WAN5_GREEN_LED,
	WAN6_GREEN_LED,
	WAN7_GREEN_LED
};
/* WAN RED LED */
enum {
	WAN0_RED_LED = WAN0_RED_LED_ID_START,
	WAN1_RED_LED,
	WAN2_RED_LED,
	WAN3_RED_LED,
	WAN4_RED_LED,
	WAN5_RED_LED,
	WAN6_RED_LED,
	WAN7_RED_LED,
	WAN0_CTRL_LED = WAN0_RED_LED_ID_START+8
};

/* WLAN LED */
enum {
    WLAN_ACT_LED = WLAN_LED_ID_START,
    WLAN_24G_ACT_LED,
    WLAN_5G_ACT_LED,
	WLAN_LED_SUPER_WIFI,
	WLAN_ONOFF_STATE_LED,
};

/* WPS LED */
enum {
	WPS_LED = WPS_LED_ID_START,
};

/* DSL LED */
enum {
    DSL_LINK_LED = DSL_LED_ID_START,
    DSL_AMBER_LED,
};

/* USB LED */
enum {
	USB_LED = USB_LED_ID_START,
	/* make this compatible with USB_HOST1_LED and USB_HOST2_LED 
	   in linux/include/sc/sc_led.h */
	USB_LED2 ,
	USB_PWR_EN ,
	WLAN_TOP_LED1 ,
	WLAN_TOP_LED2 ,
	WLAN_TOP_LED3 ,
	WLAN_TOP_LED4 ,
	WLAN_TOP_LED5 ,
	WLAN_TOP_LED6 ,
	WLAN_TOP_LED7 ,
	WLAN_TOP_LED8
};

/* USB LED */
enum{
    USB_HOST1_GREEN_LED = USB_LED_ID_START,
    USB_HOST2_GREEN_LED,
    USB_HOST1_AMBER_LED,
    USB_HOST2_AMBER_LED,
};

/* Power LED */
enum {
	PWR_GREEN_LED = PWR_LED_ID_START,
	PWR_RED_LED,
	USB_PWR_EN2,
};

/* Badge LED */
enum {
	BADGE_LED = BADGE_LED_ID_START,
};

/* MIS LED */
enum{
    LED_PCIE5_RADIOSTATE = OTHER_LED_ID_START,
    LED_PCIE24_RADIOSTATE,
    FE_LINK_ACT_LED,
    PCIE_ACT_LED,
    FXS1_FXS2_DECT_DIAL_TONE_LED,
    FXS1_FXS2_DECT_ON_HOOK_LED,
    PSTN_OUTBOUND_LED,
};

/* Push Button */
enum {
	PUSH_BTN = PUSH_BTN_ID_START,
	WPS_BTN,
	WIFI_ONOFF_BTN,
	USB_OCP_EN,
	LED_CTRL_BTN
};

#endif


