all:
	#cd src && YACC="`pwd`/../../bison/bison-1.875c/q/bin/bison -y" ./configure --host=mips-linux CC=$(CROSS)gcc --prefix=`pwd`/../qqq --disable-silent-rules
	touch src/Makefile
	cd src; make

install:
	cd src; make install

clean:
	cd src; make clean
	
