all:
	#cd src && ./configure --host=mips-linux CC=$(CROSS)gcc --prefix=`pwd`/../qqq --enable-ip6 --disable-ip4 --disable-scoped-rewrite --disable-stf
	touch src/Makefile
	cd src; make

install:
	cd src; make install

clean:
	cd src; make clean
	
